services:
    ac.recaptcha.form.type:
        class: AC\Bundle\RecaptchaBundle\Form\Type\RecaptchaType
        arguments: ["@service_container"]
        tag:
            - { name: form.type, alias: ac_recaptcha }