services:
    ac.recaptcha.form.type:
        class: AC\Bundle\RecaptchaBundle\Form\Type\RecaptchaType
        arguments: ["@service_container"]
        tags:
            - { name: form.type, alias: ac_recaptcha }

    ac.recaptcha.validator:
        class: AC\Bundle\RecaptchaBundle\Validator\Constraints\RecaptchaValidator.php
        arguments: ["@service_container"]
        tags:
    	    - { name: validator.constraint_validator, alias: ac_recaptcha_validator }